# SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-FileContributor: enriqueavi@inditex.com
#
# SPDX-License-Identifier: Apache-2.0

{{ if $.Values.createNamespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $.Values.namespace }}
{{ end }}
