# SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÃ‘O TEXTIL S.A. (INDITEX S.A.)
# SPDX-FileContributor: enriqueavi@inditex.com
#
# SPDX-License-Identifier: Apache-2.0

{{ if $.Values.createClasses}}
---
apiVersion: overcommit.inditex.dev/v1alphav1
kind: OvercommitClass
metadata:
  name: high
spec:
  cpuOvercommit: 0.1
  memoryOvercommit: 0.8
  isDefault: false
  excludedNamespaces: "{{ .Values.overcommit.excludedNamespaces }}"
  labels:
    example.com/label: "true"
  annotations:
    example.com/annotation: "true"
---
apiVersion: overcommit.inditex.dev/v1alphav1
kind: OvercommitClass
metadata:
  name: low
spec:
  cpuOvercommit: 0.8
  memoryOvercommit: 1
  isDefault: false
  excludedNamespaces: "{{ .Values.overcommit.excludedNamespaces }}"
  labels:
    example.com/label: "true"
  annotations:
    example.com/annotation: "true"
{{- end }}
