name: Check Code Generation ğŸ§ª
on:
    pull_request:
jobs:
  check-dependencies-gen:
    name: Check Go Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ§²
        uses: actions/checkout@v4

      - name: Setup Go â¬‡ï¸
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Check dependencies Generation ğŸ§ª
        run: |
            go mod tidy
            git diff  --ignore-matching-lines='.*createdAt:.*' --exit-code

  check-code-gen:
    name: Check SDK Code Generation ğŸ§ª
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ§²
        uses: actions/checkout@v4

      - name: Setup Go â¬‡ï¸
        uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Check dependencies Generation ğŸ§ª
        run: |
            make generate manifests bundle
            git diff  --ignore-matching-lines='.*createdAt:.*' --exit-code
