name: âš’ï¸ Go tests and linting for the webhook
on:
  pull_request:
jobs:
  test:
    name: Test ğŸ”¨
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ§²
      uses: actions/checkout@v4

    - name: Restore go build cache â¬
      uses: actions/cache@v4
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-v1

    - name: Setup Go â¬‡ï¸
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.2

    - name: Build and test ğŸ—ï¸
      run: |
        make build
        make test

  lint:
    name: Lint ğŸ”
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ğŸ§²
      uses: actions/checkout@v4

    - name: Restore go build cache â¬
      uses: actions/cache@v4
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-build-v1

    - name: Setup Go â¬‡ï¸
      uses: actions/setup-go@v3
      with:
        go-version: 1.24.2

    - name: Linter ğŸ”
      run: |
        make lint
